// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LunarseaResources
{
        public const string achievement_100_temp_goals = "CgkI5qishYkQEAIQGg"; // <GPGSID>
        public const string achievement_collect_250_coins = "CgkI5qishYkQEAIQCw"; // <GPGSID>
        public const string achievement_1_day = "CgkI5qishYkQEAIQIA"; // <GPGSID>
        public const string achievement_500_temp_goals = "CgkI5qishYkQEAIQGw"; // <GPGSID>
        public const string achievement_collect_2000_coins = "CgkI5qishYkQEAIQDQ"; // <GPGSID>
        public const string achievement_beat_level_2 = "CgkI5qishYkQEAIQEA"; // <GPGSID>
        public const string achievement_beat_level_3 = "CgkI5qishYkQEAIQEQ"; // <GPGSID>
        public const string achievement_collect_750_coins = "CgkI5qishYkQEAIQDA"; // <GPGSID>
        public const string achievement_beat_level_5 = "CgkI5qishYkQEAIQEw"; // <GPGSID>
        public const string achievement_first_upgrade = "CgkI5qishYkQEAIQFA"; // <GPGSID>
        public const string achievement_2000_temp_goals = "CgkI5qishYkQEAIQHA"; // <GPGSID>
        public const string achievement_5_hours = "CgkI5qishYkQEAIQHg"; // <GPGSID>
        public const string leaderboard_highest_distance_traveled_endless_mode = "CgkI5qishYkQEAIQIg"; // <GPGSID>
        public const string achievement_20_temp_goals_beat = "CgkI5qishYkQEAIQGQ"; // <GPGSID>
        public const string achievement_collect_100_coins = "CgkI5qishYkQEAIQCg"; // <GPGSID>
        public const string achievement_travel_500_m = "CgkI5qishYkQEAIQBg"; // <GPGSID>
        public const string achievement_collect_10000_coins = "CgkI5qishYkQEAIQDg"; // <GPGSID>
        public const string achievement_20_upgrades = "CgkI5qishYkQEAIQFg"; // <GPGSID>
        public const string achievement_beat_level_1 = "CgkI5qishYkQEAIQDw"; // <GPGSID>
        public const string achievement_travel_1000_m = "CgkI5qishYkQEAIQBw"; // <GPGSID>
        public const string achievement_5_upgrades = "CgkI5qishYkQEAIQFQ"; // <GPGSID>
        public const string achievement_beat_level_4 = "CgkI5qishYkQEAIQEg"; // <GPGSID>
        public const string achievement_all_upgrades_unlocked = "CgkI5qishYkQEAIQFw"; // <GPGSID>
        public const string achievement_travel_5000_m = "CgkI5qishYkQEAIQCA"; // <GPGSID>
        public const string achievement_temp_goal_beat = "CgkI5qishYkQEAIQGA"; // <GPGSID>
        public const string achievement_travel_10000_m = "CgkI5qishYkQEAIQCQ"; // <GPGSID>
        public const string achievement_2_days = "CgkI5qishYkQEAIQIQ"; // <GPGSID>
        public const string achievement_12_hours = "CgkI5qishYkQEAIQHw"; // <GPGSID>
        public const string achievement_1_hour = "CgkI5qishYkQEAIQHQ"; // <GPGSID>

}

